---
# file: roles/nfsd/tasks/main.yml
- name: packages install
  yum: name={{item}} state=present
  with_items:
    - nfs-utils

- name: create nfsd dir
  file: path="{{ nfs_dir }}" state=directory owner={{nfs_user}} group={{nfs_user}}

- name: add exportfs settings
  template: src=exports.j2 dest=/etc/exports owner=root group=root mode=0644 backup=true
  register: is_exportfs_setting
  notify: exportfs restart

- name: backup exportfs setting
  fetch:
    src={{item}}
    dest="backup/{{ansible_date_time.date}}-{{ansible_date_time.time|regex_replace(':', '')}}"
  with_items:
    - "{{is_exportfs_setting.backup_file}}"
    - /etc/exportfs
  when: is_exportfs_setting|changed

- name: delete exportfs setting backup
  file: path={{is_exportfs_setting.backup_file}} state=absent
  when: is_exportfs_setting|changed and is_exportfs_setting.backup_file is defined

- name: enable nfsd services
  service: name={{item}} state=started enabled=yes
  with_items:
    - rpcbind
    - nfs